FIO = "YANDEX.FIO"
NUMBER = "YANDEX.NUMBER"
DATETIME = "YANDEX.DATETIME"

subjects = {
    "maths": ["математика", "алгебра"],
    "geometry": "геометрия",
    "calligraphy": ["чистописание"],
    "reading": ["чтение"],
    "work": ["труд"],
    "natural": ["природовение"],
    "music": ["музыка"],
    "art": ["изобразительное искусство", "изо", "рисование"],
    "russianLanguage": ["русский язык"],
    "physicalEducation": ["физкультура", "физическая культура"],
    "nativeLanguage": ["родной язык"],
    "foundationsOfReligiousCulturesAndSecularEthics": [
        "основы религиозных культур и светской этики",
        "основы религиозных культур",
        "основы светской этики",
    ],
    "foreignLanguage": ["английский язык", "французский язык"],
    "civics": ["граждановедение"],
    "localHistory": ["краеведение"],
    "history": ["история"],
    "literature": ["литература"],
    "bls": ["обж", "основы безопасности жизнедеятельности"],
    "technology": ["технология"],
    "geography": ["география"],
    "biology": ["биология"],
    "computerScience": ["информатика", "программирование"],
    "socialStudies": ["обществознание"],
    "drawing": ["черчение"],
    "physics": ["физика"],
    "chemistry": ["химия"],
    "naturalScience": ["естествознание"],
    "fundamentalsOfEconomics": ["основы экономики", "экономика"],
    "jurisprudence": ["правоведение"],
    "philosophy": ["философия"],
    "ecology": ["экология"],
    "astronomy": ["астраномия"],
    "basicMilitaryTraining": ["нвп", "начальная военная подготовка"],
    "worldArt": [
        "мировая художественная культура",
        "МХК",
        "мировая культура",
    ],
    "rhetoric": ["риторика"],
}
