# region Base of yandex

CONFIRM = "YANDEX.CONFIRM"
REJECT = "YANDEX.REJECT"
HELP = "YANDEX.HELP"
WHAT_CAN_YOU_DO = "YANDEX.WHAT_CAN_YOU_DO"
REPEAT = "YANDEX.REPEAT"

# endregion

GET_SCHEDULE = "get_schedule"
GET_HOMEWORK = "get_homework"
